---

# Reboot the server
- name: Reboot the server
  reboot:
    reboot_timieout: 300
    tes_command: uptime
  register: Uptime
  when: Failure_Msg is undefined

# Set failure msg if server fails to reboot
- name: Set Failure message if unable to reboot
  set_fact: 
    Failure_Msg: "Unable to reboot and execute Uptime command."
  when: Uptime.rc | default('defined') != 0 

