### Failure mail when vm not exist or we are not able to fetch mac address of the vm
---
- name: Power on the VM on Vcenter
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Send email
      community.general.mail:
        host: "{{ Host }}"
        port: "25"
        from: "{{ Mail_From }}"
        to:
          - "{{ RequesterMail }}"
          - "{{ Recipients }}"
        cc: "{{ CC }}"
        subject: "OS Deplyoment Task Fail - {{ Request }} - {{ Ipr_Task_Number }} - {{ new_vm_name }}"
        body: |
          Hi Team,

          OS Deployment Task Fail.

          Reason of failure: {{ Failure_Msg }}

          Details:
            IPR Number: {{ Request }} 
            Task Number: {{ Ipr_Task_Number }}
            Server: {{ new_vm_name }}
            Domain: {{ new_vm_domain }}
            Site: {{ new_site }}
            Public IP: {{ new_vm_ip }}
            Security Zone: {{ new_sz }}
            Support Level: {{ new_supportlevel }}
            Backup IP: "{{ Backup_Ip  | default () }}"
            Storage IP: "{{ Storage_Ip | default () }}"


          Thanks & Regards,
          Automation Team

      delegate_to: localhost
